import './App.css';
import React, { useState, useRef, useEffect } from 'react'
import RecipeList from './components/RecipeList';
import { v4 as uuidv4 } from 'uuid';

function App() {
  
  /**
   * Recipes are objects with keys { id, name, ingredients, selected, false }.
   * Ingredients is an array of objects with keys { id, name, amount }.
   */
  const [recipes, setRecipes] = useState([
    {id: uuidv4(), name: "Caprese salad", ingredients: [ 
      {id: uuidv4(), name: "Tomatoes", amount: "2, sliced"},
      {id: uuidv4(), name: "Mozzarella, fresh", amount: "4 slices"},
      {id: uuidv4(), name: "Basil, fresh", amount: "8 leaves"},
      {id: uuidv4(), name: "Olive oil", amount: "drizzle"},
      {id: uuidv4(), name: "Salt/pepper", amount: "to taste"},
      ], selected: false, editing: false},
    {id: uuidv4(), name: "Strawberry Banana Smoothie", ingredients: [ 
      {id: uuidv4(), name: "Bananas", amount: "2, peeled"},
      {id: uuidv4(), name: "Strawberries", amount: "1/2 C"},
      {id: uuidv4(), name: "Milk", amount: "6oz"},
      ], selected: false, editing: false},
  ])
  const [prevRecipes, setPrevRecipes] = useState([])
  const recipeNameRef = useRef()
  const searchRef = useRef()

  // local storage setup
  const LOCAL_STORAGE_KEY = 'recipeApp.recipes'

  // local storage setup
  useEffect(() => {
    const storedRecipes = JSON.parse(localStorage.getItem(LOCAL_STORAGE_KEY))
    if (storedRecipes) setRecipes(storedRecipes)
  }, [])

  // local storage setup
  useEffect(() => {
    localStorage.setItem(LOCAL_STORAGE_KEY, JSON.stringify(recipes))
  }, [recipes])
  
  function handleAddRecipe() {
    /**
     * Gets name ref, then creates/adds a new object to the 'recipes' array.
     */
    const name = recipeNameRef.current.value
    if (name === '') return // if name is blank, do not add anything to array
    setRecipes(prev => {
      return [...prev, 
        { 
          id: uuidv4(), 
          name: name, 
          ingredients: [],
          selected: false,
          editing: false
        }
      ]
    })
    console.log(`added ${name} to recipes`)
    recipeNameRef.current.value = null
  }

  function storeRecipes() {
    /**
     * Stores current 'recipes' array in 'prevRecipes' array.
     */
    console.log('storing current recipes array in prevRecipes')
    setPrevRecipes(recipes)
  }

  function restoreRecipes() {
    /**
     * Sets current 'recipes' array to 'prevRecipes' array.
     */
    console.log('restoring recipes array from prevRecipes')
    setRecipes(prevRecipes)
  }

  function removeRecipe(id) {
    /**
     * Removes 'recipe' from 'recipes' array based on id.
     * @param {String} id  UUID generated by uuidv4.
     * 
     */
    storeRecipes()
    const newRecipes = recipes.filter(recipe => recipe.id !== id)
    setRecipes(newRecipes)
  }
  
  function handleClearAll() {
    /**
     * Stores current 'recipes' array in 'prevRecipes', then clears it.
     */
    storeRecipes()
    console.log('clearing recipes array')
    setRecipes([])
  }

  function handleKeyPress(event) {
    /**
     * Calls 'handleAddRecipe' when 'Enter' key is pressed.
     * The keycode for 'Enter' is 13.
     * @param event  Keypress event watching for 'Enter' key.
     */
    if (event.keyCode === 13 || event.which === 13) {
      handleAddRecipe()
    }
  }

  function addIngredient(id, name, amount) {
    /**
     * Adds ingredient to 'ingredients' array for a given recipe id.
     * Used in the RecipeInfo component.
     * @param {String} id      UUID generated by uuidv4.
     * @param {String} name    Name of ingredient.
     * @param {String} amount  Amount of ingredient.
     */
    const newRecipes = [...recipes]
    const recipe = newRecipes.find(recipe => recipe.id === id)
    const newIngredient = {id: uuidv4(), name: name, amount: amount}
    recipe.ingredients.push(newIngredient)
    setRecipes(newRecipes)
    console.log(`${newIngredient.name} added to ${recipe.name}`)
  }

  function removeIngredient(recipeId, ingredientId) {
    /**
     * Removes ingredient  from recipe based on recipe id and ingredient id.
     * Used in the IngredientsList component.
     * @param {String} id  UUID generated by uuidv4.
     * @param {String} id  UUID generated by uuidv4.
     */
    const newRecipes = [...recipes]
    const recipe = newRecipes.find(recipe => recipe.id === recipeId)
    recipe.ingredients = recipe.ingredients.filter(ingredient => ingredient.id !== ingredientId)
    setRecipes(newRecipes)
  }

  function searchIngredients(query, recipe) {
    /**
     * Searches given 'recipe' object's 'ingredients' array for given query.
     * Matches are case insensitive.
     * @param  {String}  query   String to search for.
     * @param  {Object}  recipe  Recipe to search.
     * @return {Boolean}         True if ingredient name contains the given query string. 
     */
    let found = false
    recipe.ingredients.forEach(ingredient => {
      console.log(`searching for ${query} in ${recipe.name}`)
      if (ingredient.name.toLowerCase().includes(query)) {
        found = true
      }
    })
    return found
  }

  function handleSearch() {
    /**
     * Filters 'recipes' array based on matches from the 'searchRef' ref.
     * Calls 'searchIngredients' during filter.
     * Matches are case insensitive.
     * Sets 'recipes' array to filtered array.
     */
    storeRecipes()
    const query = searchRef.current.value.toLowerCase()
    const searchResults = recipes.filter(recipe => 
      recipe.name.toLowerCase().includes(query) || searchIngredients(query, recipe))
    setRecipes(searchResults)
    searchRef.current.value = null
  }

  function handleRestore() {
    /**
     * Returns recipes list to previous state after search filter.
     */
    restoreRecipes()
  }

  return (
    <>
      <div className='container--app'>
        <div className='container container--header'>
          <div className='container--header__title'>
            Recipes
          </div>
          
          <div className='container--header__addRecipe'>
            <input 
              placeholder='Recipe Name' 
              type='text'
              ref={recipeNameRef} 
              onKeyPress={handleKeyPress}
            />
            <span className='pad-left' >
              <button 
                onClick={handleAddRecipe}
              > Add</button>
            </span>
          </div>
          <div>
            <input type='text' placeholder='Search' ref={searchRef} />
            <span className='pad-left'>
              <button onClick={handleSearch}>Search</button>
            </span>
          </div>

          <div>
            <button onClick={handleRestore}>Restore</button>
            <button onClick={handleClearAll}>Clear All</button>
          </div>
        </div>

        <div >
          <div className='container'>
            <RecipeList
              recipes={recipes}
              removeRecipe={removeRecipe}
              addIngredient={addIngredient}
              removeIngredient={removeIngredient}
            />
          </div>
        </div>
      </div>
    </>
  );
}

export default App;
